// src/config/products.config.ts

export interface ProductImage {
  src: string;
  alt: string;
  isPrimary?: boolean;
}

export interface Product {
  id: string;
  sku: string;
  slug: string;
  name: string;
  category: string;
  brand: string;
  shortDescription: string;
  description: string;
  images: ProductImage[];
  priceRange: {
    min: number;
    max: number;
    currency: 'TL';
    note?: string;
  };
  specs: {
    material: string;
    width: string;
    height: string;
    thickness: string;
    lockSystem: string;
    insulation: string;
    color: string[];
    warranty: string;
    fireRating?: string;
    securityClass?: string;
  };
  features: string[];
  badge?: 'Yeni' | 'Popüler' | 'Çok Satan' | 'Kampanyalı' | 'Sınırlı Stok';
  isNew?: boolean;
  isFeatured?: boolean;
  relatedProducts?: string[];
}

export const productCategories = [
  {
    id: 'celik-kapilar',
    title: 'Çelik Kapılar',
    description: 'Yüksek güvenlikli, ses ve ısı yalıtımlı çelik kapı modelleri.',
    icon: 'Shield',
    image: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1200&h=600&fit=crop',
    productCount: 3,
  },
  {
    id: 'ic-kapilar',
    title: 'İç Kapılar (Oda Kapıları)',
    description: 'Lake, laminat, membran ve masif iç kapı modelleri.',
    icon: 'DoorOpen',
    image: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1200&h=600&fit=crop',
    productCount: 19,
  },
  {
    id: 'villa-kapilari',
    title: 'Villa Kapıları',
    description: 'Prestijli ve şık villa giriş kapıları.',
    icon: 'Home',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&h=600&fit=crop',
    productCount: 2,
  },
  {
    id: 'amerikan-panel-kapilar',
    title: 'Amerikan Panel Kapılar',
    description: 'Ekonomik ve dayanıklı amerikan panel kapı çeşitleri.',
    icon: 'LayoutGrid',
    image: 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=1200&h=600&fit=crop',
    productCount: 1,
  },
  {
    id: 'cam-kapilar',
    title: 'Cam Kapılar & Sürgülü Sistemler',
    description: 'Temperli cam kapılar ve sürgülü sistemler.',
    icon: 'Maximize',
    image: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=1200&h=600&fit=crop',
    productCount: 1,
  },
  {
    id: 'yangin-kapilari',
    title: 'Yangın Kapıları',
    description: 'Sertifikalı yangın kapıları. 60-120 dk yangın dayanımı.',
    icon: 'Flame',
    image: 'https://images.unsplash.com/photo-1600573472591-ee6b68d14c68?w=1200&h=600&fit=crop',
    productCount: 2,
  },
];

export const compareColumns = [
  { key: 'material', label: 'Malzeme' },
  { key: 'width', label: 'Genişlik' },
  { key: 'height', label: 'Yükseklik' },
  { key: 'thickness', label: 'Kalınlık' },
  { key: 'lockSystem', label: 'Kilit Sistemi' },
  { key: 'insulation', label: 'Yalıtım' },
  { key: 'color', label: 'Renk Seçenekleri' },
  { key: 'warranty', label: 'Garanti' },
  { key: 'fireRating', label: 'Yangın Dayanımı' },
  { key: 'securityClass', label: 'Güvenlik Sınıfı' },
];

export const products: Product[] = [
  // --- ÇELİK KAPILAR ---
  {
    id: 'celik-001',
    sku: 'KA-CK-001',
    slug: 'guardian-elite-celik-kapi',
    name: 'Guardian Elite Çelik Kapı',
    category: 'celik-kapilar',
    brand: 'KaleKilit',
    shortDescription: 'Çok noktalı kilit sistemi, çift çelik levha, yüksek ses ve ısı yalıtımı.',
    description: `Guardian Elite, KaleKilit'in en üst segment çelik kapı serisidir. Çift katmanlı çelik levha yapısı, 7 noktalı kilit sistemi ve taş yünü yalıtım ile evinize maksimum güvenlik ve konfor sağlar.

## Öne Çıkan Özellikler
- EN 1627 RC3 sınıfı güvenlik
- 42 dB ses yalıtımı
- Parmak izi + şifre kilit seçeneği
- 14 farklı dış kaplama seçeneği`,
    images: [
      { src: 'https://images.unsplash.com/photo-1600047509358-9dc75507daeb?w=800&h=1000&fit=crop', alt: 'Guardian Elite Çelik Kapı - Ön Görünüm', isPrimary: true },
      { src: 'https://images.unsplash.com/photo-1600047509358-9dc75507daeb?w=1200&h=900&fit=crop', alt: 'Guardian Elite Çelik Kapı - Açık Durum' },
      { src: 'https://images.unsplash.com/photo-1600047509358-9dc75507daeb?w=600&h=600&fit=crop&crop=bottom', alt: 'Guardian Elite - Kilit Detayı' },
      { src: 'https://images.unsplash.com/photo-1600047509358-9dc75507daeb?w=1200&h=900&fit=crop&crop=top', alt: 'Guardian Elite - İç Yüz Görünüm' },
    ],
    priceRange: { min: 18000, max: 28000, currency: 'TL', note: 'Montaj dahil fiyat' },
    specs: {
      material: 'Çift Katmanlı Çelik (1.2mm + 0.8mm)',
      width: '90 cm / 100 cm',
      height: '200 cm / 210 cm',
      thickness: '90 mm',
      lockSystem: '7 Noktalı Çelik Kilit (KaleKilit)',
      insulation: 'Taş Yünü - 42 dB Ses / 1.8 W/m²K Isı',
      color: ['Ceviz', 'Venge', 'Beyaz', 'Antrasit', 'Meşe', 'Beton'],
      warranty: '10 Yıl',
      securityClass: 'RC3 (EN 1627)',
    },
    features: [
      '7 Noktalı Çelik Kilit Sistemi',
      'Çift Çelik Levha Yapısı',
      'Parmak İzi / Şifre Kilit Seçeneği',
      'Yüksek Ses & Isı Yalıtımı',
      '14 Kaplama Seçeneği',
      'Anti-bumber Silindir',
    ],
    badge: 'Popüler',
    isFeatured: true,
    relatedProducts: ['fortress-pro-celik-kapi', 'smart-guard-celik-kapi'],
  },
  {
    id: 'celik-002',
    sku: 'KA-CK-002',
    slug: 'fortress-pro-celik-kapi',
    name: 'Fortress Pro Çelik Kapı',
    category: 'celik-kapilar',
    brand: 'KaleKilit',
    shortDescription: 'Giriş seviye yüksek güvenlik çelik kapı. 5 noktalı kilit, standart yalıtım.',
    description: 'Fortress Pro, kaliteden ödün vermeden uygun fiyatlı çelik kapı arayanlar için ideal seçimdir. 5 noktalı kilit sistemi ve poliüretan yalıtım ile temel güvenlik ve konfor ihtiyaçlarınızı karşılar.',
    images: [
      { src: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&h=1000&fit=crop', alt: 'Fortress Pro Çelik Kapı', isPrimary: true },
      { src: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1200&h=900&fit=crop', alt: 'Fortress Pro - Yan Görünüm' },
      { src: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=600&h=600&fit=crop&crop=bottom', alt: 'Fortress Pro - Kilit Sistemi' },
    ],
    priceRange: { min: 12000, max: 18000, currency: 'TL', note: 'Montaj dahil fiyat' },
    specs: {
      material: 'Tek Katmanlı Çelik (1.2mm)',
      width: '90 cm',
      height: '200 cm',
      thickness: '70 mm',
      lockSystem: '5 Noktalı Çelik Kilit',
      insulation: 'Poliüretan Köpük - 35 dB Ses',
      color: ['Ceviz', 'Venge', 'Beyaz', 'Antrasit'],
      warranty: '5 Yıl',
      securityClass: 'RC2 (EN 1627)',
    },
    features: ['5 Noktalı Kilit', 'Poliüretan Yalıtım', '8 Kaplama Seçeneği'],
    badge: 'Çok Satan',
    isFeatured: true,
    relatedProducts: ['guardian-elite-celik-kapi'],
  },
  {
    id: 'celik-003',
    sku: 'KA-CK-003',
    slug: 'smart-guard-celik-kapi',
    name: 'Smart Guard Akıllı Çelik Kapı',
    category: 'celik-kapilar',
    brand: 'KaleKilit',
    shortDescription: 'Akıllı kilit sistemli, Wi-Fi bağlantılı, uzaktan kontrol edilebilir çelik kapı.',
    description: 'Smart Guard, teknoloji tutkunları için tasarlanmış akıllı çelik kapı modelidir. Wi-Fi bağlantılı kilit sayesinde telefonunuzdan kapınızı kontrol edebilir, giriş kaydı tutabilirsiniz.',
    images: [
      { src: 'https://images.unsplash.com/photo-1600573472592-401b489a3cdc?w=800&h=1000&fit=crop', alt: 'Smart Guard Akıllı Çelik Kapı', isPrimary: true },
      { src: 'https://images.unsplash.com/photo-1600573472592-401b489a3cdc?w=1200&h=900&fit=crop', alt: 'Smart Guard - Kontrol Paneli' },
    ],
    priceRange: { min: 25000, max: 38000, currency: 'TL', note: 'Montaj + kurulum dahil' },
    specs: {
      material: 'Çift Katmanlı Çelik (1.5mm + 1.0mm)',
      width: '90 cm / 100 cm',
      height: '200 cm / 210 cm',
      thickness: '95 mm',
      lockSystem: 'Akıllı Kilit (Wi-Fi + Parmak İzi + Şifre + Kart)',
      insulation: 'Taş Yünü + Kauçuk Conta - 45 dB Ses',
      color: ['Antrasit', 'Siyah', 'Gümüş', 'Bronz'],
      warranty: '10 Yıl',
      securityClass: 'RC3 (EN 1627)',
    },
    features: [
      'Wi-Fi Bağlantılı Akıllı Kilit',
      'Mobil Uygulama ile Uzaktan Kontrol',
      'Parmak İzi + Şifre + Kart Giriş',
      'Giriş Kaydı Tutma',
      'Acil Durum Mekanik Anahtar',
    ],
    badge: 'Yeni',
    isFeatured: true,
    relatedProducts: ['guardian-elite-celik-kapi', 'fortress-pro-celik-kapi'],
  },

  // --- İÇ KAPILAR ---
  {
    id: 'ic-001',
    sku: 'KA-IK-001',
    slug: 'elegance-beyaz-citali-ic-kapi',
    name: 'Elegance Beyaz Çıtalı İç Kapı',
    category: 'ic-kapilar',
    brand: 'KapıArt Özel Üretim',
    shortDescription: 'Dikey çıta detaylı, mat beyaz lake, gri pervazlı modern iç kapı.',
    description: 'Elegance serisi, dikey çıta detaylarıyla klasik çizgileri modern bir yorumla sunan lake iç kapı modelidir. Gri pervaz ve siyah aksesuar kombinasyonuyla şık bir görünüm sağlar.',
    images: [
      { src: '/kapi/ic-kapi-01/kapi-sahne.webp', alt: 'Elegance Beyaz Çıtalı İç Kapı - Mekan Görünümü', isPrimary: true },
      { src: '/kapi/ic-kapi-01/kapi-detay.webp', alt: 'Elegance Beyaz Çıtalı İç Kapı - Detay' },
      { src: '/kapi/ic-kapi-01/kapi-yakin.webp', alt: 'Elegance Beyaz Çıtalı İç Kapı - Yakın Çekim' },
    ],
    priceRange: { min: 5500, max: 7500, currency: 'TL', note: 'Kasa + Kanat + Pervaz' },
    specs: {
      material: 'MDF üzeri Lake Boya',
      width: '80 cm / 90 cm',
      height: '200 cm / 210 cm',
      thickness: '40 mm',
      lockSystem: 'Manyetik Kilit (Sessiz)',
      insulation: 'Standart',
      color: ['Mat Beyaz', 'Krem', 'Gri'],
      warranty: '5 Yıl',
    },
    features: [
      'Dikey Çıta Detay Tasarımı',
      'Mat Lake Boya (3 Kat Astar)',
      'Gizli Menteşe Sistemi',
      'Manyetik Kilit (Sessiz Kapanma)',
      'Özel Ölçü İmkânı',
    ],
    badge: 'Yeni',
    isFeatured: true,
    relatedProducts: ['minimal-beyaz-panel-ic-kapi', 'flora-beyaz-lake-ic-kapi'],
  },
  {
    id: 'ic-002',
    sku: 'KA-IK-002',
    slug: 'vista-camli-beyaz-ic-kapi',
    name: 'Vista Camlı Beyaz İç Kapı',
    category: 'ic-kapilar',
    brand: 'KapıArt Özel Üretim',
    shortDescription: 'Tek parça buzlu cam panelli, gri pervazlı, modern minimalist camlı iç kapı.',
    description: 'Vista serisi, geniş buzlu cam paneliyle mekanlara doğal ışık geçişi sağlayan modern iç kapı modelidir. Minimalist çerçeve tasarımı ve gri pervaz detayıyla çağdaş iç mekanlara mükemmel uyum sağlar.',
    images: [
      { src: '/kapi/ic-kapi-02/kapi-sahne.webp', alt: 'Vista Camlı Beyaz İç Kapı - Mekan Görünümü', isPrimary: true },
      { src: '/kapi/ic-kapi-02/kapi-detay.webp', alt: 'Vista Camlı Beyaz İç Kapı - Detay' },
      { src: '/kapi/ic-kapi-02/kapi-yakin.webp', alt: 'Vista Camlı Beyaz İç Kapı - Yakın Çekim' },
    ],
    priceRange: { min: 6500, max: 9000, currency: 'TL', note: 'Kasa + Kanat + Pervaz' },
    specs: {
      material: 'MDF + Buzlu Temperli Cam',
      width: '80 cm / 90 cm',
      height: '200 cm / 210 cm',
      thickness: '40 mm',
      lockSystem: 'Manyetik Kilit (Sessiz)',
      insulation: 'Standart',
      color: ['Mat Beyaz', 'Krem', 'Antrasit'],
      warranty: '5 Yıl',
    },
    features: [
      'Tek Parça Buzlu Temperli Cam',
      'Doğal Işık Geçişi',
      'Gizli Menteşe Sistemi',
      'Manyetik Sessiz Kilit',
      'Özel Ölçü İmkânı',
    ],
    badge: 'Popüler',
    isFeatured: true,
    relatedProducts: ['panorama-4-camli-beyaz-ic-kapi', 'klasik-8-camli-beyaz-ic-kapi'],
  },
  {
    id: 'ic-003',
    sku: 'KA-IK-003',
    slug: 'luna-mese-vitray-camli-ic-kapi',
    name: 'Luna Meşe Vitray Camlı İç Kapı',
    category: 'ic-kapilar',
    brand: 'KapıArt Özel Üretim',
    shortDescription: 'Açık meşe laminat, hilal formunda dekoratif vitray cam detaylı iç kapı.',
    description: 'Luna serisi, hilal formundaki vitray cam detayıyla geleneksel Türk sanatını modern kapı tasarımıyla buluşturur. Açık meşe laminat kaplama ile sıcak ve doğal bir görünüm sunar.',
    images: [
      { src: '/kapi/ic-kapi-03/kapi-sahne.webp', alt: 'Luna Meşe Vitray Camlı İç Kapı - Mekan Görünümü', isPrimary: true },
      { src: '/kapi/ic-kapi-03/kapi-yakin.webp', alt: 'Luna Meşe Vitray Camlı İç Kapı - Yakın Çekim' },
      { src: '/kapi/ic-kapi-03/kapi-detay.webp', alt: 'Luna Meşe Vitray Camlı İç Kapı - Detay' },
    ],
    priceRange: { min: 7000, max: 10000, currency: 'TL', note: 'Kasa + Kanat + Pervaz' },
    specs: {
      material: 'MDF üzeri Laminat + Vitray Cam',
      width: '80 cm / 90 cm',
      height: '200 cm / 210 cm',
      thickness: '40 mm',
      lockSystem: 'Silindir Kilit',
      insulation: 'Standart',
      color: ['Açık Meşe', 'Doğal Meşe', 'Koyu Ceviz'],
      warranty: '5 Yıl',
    },
    features: [
      'Hilal Formunda Vitray Cam',
      'Dekoratif Çiçek Deseni',
      'CPL Laminat Kaplama',
      'Doğal Ahşap Görünümü',
      'Özel Ölçü İmkânı',
    ],
    isFeatured: true,
    relatedProducts: ['elegance-beyaz-citali-ic-kapi', 'art-deco-mese-ic-kapi'],
  },
  {
    id: 'ic-004',
    sku: 'KA-IK-004',
    slug: 'art-deco-mese-ic-kapi',
    name: 'Art Deco Meşe İç Kapı',
    category: 'ic-kapilar',
    brand: 'KapıArt Özel Üretim',
    shortDescription: 'Geometrik yarım daire CNC desenli, açık meşe, dekoratif iç kapı.',
    description: 'Art Deco serisi, CNC ile işlenmiş geometrik yarım daire deseniyle Art Deco akımından ilham alan zarif bir iç kapı modelidir. Açık meşe laminat kaplamayla sıcak ve şık bir atmosfer yaratır.',
    images: [
      { src: '/kapi/ic-kapi-04/kapi-sahne.webp', alt: 'Art Deco Meşe İç Kapı - Mekan Görünümü', isPrimary: true },
      { src: '/kapi/ic-kapi-04/kapi-detay.webp', alt: 'Art Deco Meşe İç Kapı - Detay' },
      { src: '/kapi/ic-kapi-04/kapi-yakin.webp', alt: 'Art Deco Meşe İç Kapı - Yakın Çekim' },
    ],
    priceRange: { min: 6000, max: 8500, currency: 'TL', note: 'Kasa + Kanat + Pervaz' },
    specs: {
      material: 'MDF üzeri CPL Laminat',
      width: '80 cm / 90 cm',
      height: '200 cm / 210 cm',
      thickness: '40 mm',
      lockSystem: 'Silindir Kilit',
      insulation: 'Standart',
      color: ['Açık Meşe', 'Krem Meşe', 'Gri Meşe'],
      warranty: '5 Yıl',
    },
    features: [
      'CNC İşlemeli Geometrik Desen',
      'Art Deco Tasarım Çizgisi',
      'CPL Laminat (Çizilmez)',
      'Doğal Ahşap Görünümü',
      'Özel Ölçü İmkânı',
    ],
    relatedProducts: ['luna-mese-vitray-camli-ic-kapi', 'elegance-beyaz-citali-ic-kapi'],
  },
  {
    id: 'ic-005',
    sku: 'KA-IK-005',
    slug: 'royal-beyaz-vitray-camli-ic-kapi',
    name: 'Royal Beyaz Vitray Camlı İç Kapı',
    category: 'ic-kapilar',
    brand: 'KapıArt Özel Üretim',
    shortDescription: 'Dekoratif taç pervazlı, vitray camlı, beyaz lake klasik iç kapı.',
    description: 'Royal serisi, dekoratif taç pervaz ve yaprak motifli vitray cam detayıyla klasik iç mekanlara prestij katan lake iç kapı modelidir. El işçiliğini andıran kabartma desenleriyle zamansız bir estetik sunar.',
    images: [
      { src: '/kapi/ic-kapi-05/kapi-sahne.webp', alt: 'Royal Beyaz Vitray Camlı İç Kapı - Mekan Görünümü', isPrimary: true },
      { src: '/kapi/ic-kapi-05/kapi-yakin.webp', alt: 'Royal Beyaz Vitray Camlı İç Kapı - Yakın Çekim' },
      { src: '/kapi/ic-kapi-05/kapi-detay.webp', alt: 'Royal Beyaz Vitray Camlı İç Kapı - Detay' },
    ],
    priceRange: { min: 8000, max: 12000, currency: 'TL', note: 'Kasa + Kanat + Pervaz + Taç' },
    specs: {
      material: 'MDF üzeri Lake Boya + Vitray Cam',
      width: '80 cm / 90 cm',
      height: '200 cm / 210 cm',
      thickness: '40 mm',
      lockSystem: 'Manyetik Kilit (Sessiz)',
      insulation: 'Standart',
      color: ['Mat Beyaz', 'Parlak Beyaz', 'Krem'],
      warranty: '5 Yıl',
    },
    features: [
      'Dekoratif Taç Pervaz',
      'Vitray Cam Panel',
      'Yaprak Motifli Kabartma Desen',
      'Mat Lake Boya (3 Kat Astar)',
      'Klasik Tasarım Çizgisi',
    ],
    badge: 'Kampanyalı',
    isFeatured: true,
    relatedProducts: ['flora-beyaz-lake-ic-kapi', 'klasik-8-camli-beyaz-ic-kapi'],
  },
  {
    id: 'ic-006',
    sku: 'KA-IK-006',
    slug: 'flora-beyaz-lake-ic-kapi',
    name: 'Flora Beyaz Lake İç Kapı',
    category: 'ic-kapilar',
    brand: 'KapıArt Özel Üretim',
    shortDescription: 'Yaprak desenli CNC işlemeli, taç pervazlı, beyaz lake klasik iç kapı.',
    description: 'Flora serisi, doğadan ilham alan yaprak motifli CNC kabartma deseniyle zarif bir iç kapı modelidir. Dekoratif taç pervaz detayıyla klasik ve gösterişli mekanlara uyum sağlar.',
    images: [
      { src: '/kapi/ic-kapi-06/kapi-sahne.webp', alt: 'Flora Beyaz Lake İç Kapı - Mekan Görünümü', isPrimary: true },
      { src: '/kapi/ic-kapi-06/kapi-detay.webp', alt: 'Flora Beyaz Lake İç Kapı - Detay' },
      { src: '/kapi/ic-kapi-06/kapi-yakin.webp', alt: 'Flora Beyaz Lake İç Kapı - Yakın Çekim' },
    ],
    priceRange: { min: 7500, max: 10500, currency: 'TL', note: 'Kasa + Kanat + Pervaz + Taç' },
    specs: {
      material: 'MDF üzeri Lake Boya',
      width: '80 cm / 90 cm',
      height: '200 cm / 210 cm',
      thickness: '40 mm',
      lockSystem: 'Manyetik Kilit (Sessiz)',
      insulation: 'Standart',
      color: ['Mat Beyaz', 'Parlak Beyaz', 'Krem'],
      warranty: '5 Yıl',
    },
    features: [
      'Yaprak Motifli CNC Desen',
      'Dekoratif Taç Pervaz',
      'Mat Lake Boya (3 Kat Astar)',
      'Gizli Menteşe Sistemi',
      'Özel Ölçü İmkânı',
    ],
    relatedProducts: ['royal-beyaz-vitray-camli-ic-kapi', 'elegance-beyaz-citali-ic-kapi'],
  },
  {
    id: 'ic-007',
    sku: 'KA-IK-007',
    slug: 'panorama-4-camli-beyaz-ic-kapi',
    name: 'Panorama 4 Camlı Beyaz İç Kapı',
    category: 'ic-kapilar',
    brand: 'KapıArt Özel Üretim',
    shortDescription: '4 bölmeli buzlu cam panelli, beyaz lake, modern minimalist camlı iç kapı.',
    description: 'Panorama serisi, yatay bölmeli 4 buzlu cam paneliyle mekanlara maksimum ışık geçişi sağlayan modern iç kapı modelidir. Sade çizgileri ve beyaz lake yüzeyiyle minimalist iç mekanlara mükemmel uyum sağlar.',
    images: [
      { src: '/kapi/ic-kapi-07/kapi-sahne.webp', alt: 'Panorama 4 Camlı Beyaz İç Kapı - Mekan Görünümü', isPrimary: true },
      { src: '/kapi/ic-kapi-07/kapi-yakin.webp', alt: 'Panorama 4 Camlı Beyaz İç Kapı - Yakın Çekim' },
      { src: '/kapi/ic-kapi-07/kapi-detay.webp', alt: 'Panorama 4 Camlı Beyaz İç Kapı - Detay' },
    ],
    priceRange: { min: 7000, max: 9500, currency: 'TL', note: 'Kasa + Kanat + Pervaz' },
    specs: {
      material: 'MDF + Buzlu Temperli Cam',
      width: '80 cm / 90 cm',
      height: '200 cm / 210 cm',
      thickness: '40 mm',
      lockSystem: 'Manyetik Kilit (Sessiz)',
      insulation: 'Standart',
      color: ['Mat Beyaz', 'Krem', 'Gri'],
      warranty: '5 Yıl',
    },
    features: [
      '4 Bölmeli Buzlu Temperli Cam',
      'Yüksek Işık Geçirgenliği',
      'Gizli Menteşe Sistemi',
      'Manyetik Sessiz Kilit',
      'Modern Minimalist Tasarım',
    ],
    relatedProducts: ['vista-camli-beyaz-ic-kapi', 'klasik-8-camli-beyaz-ic-kapi'],
  },
  {
    id: 'ic-008',
    sku: 'KA-IK-008',
    slug: 'klasik-8-camli-beyaz-ic-kapi',
    name: 'Klasik 8 Camlı Beyaz İç Kapı',
    category: 'ic-kapilar',
    brand: 'KapıArt Özel Üretim',
    shortDescription: '8 bölmeli buzlu cam panelli, beyaz lake, klasik çerçeveli camlı iç kapı.',
    description: 'Klasik serisi, 8 bölmeli buzlu cam paneliyle geleneksel iç mekan tasarımlarına uyum sağlayan zarif bir iç kapı modelidir. Dekoratif pervaz detaylarıyla klasik şıklığı modern konforla birleştirir.',
    images: [
      { src: '/kapi/ic-kapi-08/kapi-sahne.webp', alt: 'Klasik 8 Camlı Beyaz İç Kapı - Mekan Görünümü', isPrimary: true },
      { src: '/kapi/ic-kapi-08/kapi-detay.webp', alt: 'Klasik 8 Camlı Beyaz İç Kapı - Detay' },
      { src: '/kapi/ic-kapi-08/kapi-yakin.webp', alt: 'Klasik 8 Camlı Beyaz İç Kapı - Yakın Çekim' },
    ],
    priceRange: { min: 7500, max: 10500, currency: 'TL', note: 'Kasa + Kanat + Pervaz' },
    specs: {
      material: 'MDF + Buzlu Temperli Cam',
      width: '80 cm / 90 cm',
      height: '200 cm / 210 cm',
      thickness: '40 mm',
      lockSystem: 'Manyetik Kilit (Sessiz)',
      insulation: 'Standart',
      color: ['Mat Beyaz', 'Parlak Beyaz', 'Krem'],
      warranty: '5 Yıl',
    },
    features: [
      '8 Bölmeli Buzlu Temperli Cam',
      'Klasik Çerçeve Detayı',
      'Doğal Işık Geçişi',
      'Dekoratif Pervaz',
      'Gizli Menteşe Sistemi',
    ],
    badge: 'Çok Satan',
    isFeatured: true,
    relatedProducts: ['panorama-4-camli-beyaz-ic-kapi', 'royal-beyaz-vitray-camli-ic-kapi'],
  },
  {
    id: 'ic-009',
    sku: 'KA-IK-009',
    slug: 'minimal-beyaz-panel-ic-kapi',
    name: 'Minimal Beyaz Panel İç Kapı',
    category: 'ic-kapilar',
    brand: 'KapıArt Özel Üretim',
    shortDescription: 'Sade çerçeveli, düz panelli, beyaz lake minimalist iç kapı.',
    description: 'Minimal serisi, sade ve temiz çizgileriyle minimalist iç mekanlara mükemmel uyum sağlayan lake iç kapı modelidir. İç içe geçmiş ince çerçeve detayıyla sadelikte zarafet sunar.',
    images: [
      { src: '/kapi/ic-kapi-09/kapi-sahne.webp', alt: 'Minimal Beyaz Panel İç Kapı - Mekan Görünümü', isPrimary: true },
      { src: '/kapi/ic-kapi-09/kapi-detay.webp', alt: 'Minimal Beyaz Panel İç Kapı - Detay' },
      { src: '/kapi/ic-kapi-09/kapi-yakin.webp', alt: 'Minimal Beyaz Panel İç Kapı - Yakın Çekim' },
    ],
    priceRange: { min: 4500, max: 6500, currency: 'TL', note: 'Kasa + Kanat + Pervaz' },
    specs: {
      material: 'MDF üzeri Lake Boya',
      width: '80 cm / 90 cm',
      height: '200 cm / 210 cm',
      thickness: '40 mm',
      lockSystem: 'Manyetik Kilit (Sessiz)',
      insulation: 'Standart',
      color: ['Mat Beyaz', 'Krem', 'Gri', 'Antrasit'],
      warranty: '5 Yıl',
    },
    features: [
      'Sade Çerçeve Detaylı Panel',
      'Mat Lake Boya (3 Kat Astar)',
      'Gizli Menteşe Sistemi',
      'Manyetik Kilit (Sessiz Kapanma)',
      'Modern Minimalist Tasarım',
    ],
    isFeatured: true,
    relatedProducts: ['elegance-beyaz-citali-ic-kapi', 'flora-beyaz-lake-ic-kapi'],
  },
  {
    id: 'ic-010',
    sku: 'KA-IK-010',
    slug: 'heritage-klasik-3-panelli-ic-kapi',
    name: 'Heritage Klasik 3 Panelli İç Kapı',
    category: 'ic-kapilar',
    brand: 'KapıArt Özel Üretim',
    shortDescription: 'Klasik 3 panelli, beyaz/krem lake, dekoratif pervazlı geleneksel iç kapı.',
    description: 'Heritage serisi, geleneksel 3 panel tasarımıyla klasik iç mekanlara zarif bir dokunuş katan lake iç kapı modelidir. Dekoratif pervaz profilleriyle zamansız bir estetik sunar.',
    images: [
      { src: '/kapi/ic-kapi-10/kapi-sahne.webp', alt: 'Heritage Klasik 3 Panelli İç Kapı - Mekan Görünümü', isPrimary: true },
      { src: '/kapi/ic-kapi-10/kapi-detay.webp', alt: 'Heritage Klasik 3 Panelli İç Kapı - Detay' },
      { src: '/kapi/ic-kapi-10/kapi-yakin.webp', alt: 'Heritage Klasik 3 Panelli İç Kapı - Yakın Çekim' },
    ],
    priceRange: { min: 5000, max: 7000, currency: 'TL', note: 'Kasa + Kanat + Pervaz' },
    specs: {
      material: 'MDF üzeri Lake Boya',
      width: '80 cm / 90 cm',
      height: '200 cm / 210 cm',
      thickness: '40 mm',
      lockSystem: 'Manyetik Kilit (Sessiz)',
      insulation: 'Standart',
      color: ['Mat Beyaz', 'Krem', 'Bej'],
      warranty: '5 Yıl',
    },
    features: [
      'Klasik 3 Panel Tasarımı',
      'Dekoratif Pervaz Profili',
      'Mat Lake Boya (3 Kat Astar)',
      'Gizli Menteşe Sistemi',
      'Manyetik Kilit (Sessiz Kapanma)',
    ],
    relatedProducts: ['minimal-beyaz-panel-ic-kapi', 'elegance-beyaz-citali-ic-kapi'],
  },

  // --- YENİ SERİ (ic-kapi-11 to ic-kapi-19) ---
  {
    id: 'ic-011',
    sku: 'KA-IK-011',
    slug: 'modern-gri-citali-ic-kapi',
    name: 'Modern Gri Çıtalı İç Kapı',
    category: 'ic-kapilar',
    brand: 'KapıArt Özel Üretim',
    shortDescription: 'Dikey çıta detaylı, mat gri lake, minimalist modern iç kapı.',
    description: 'Modern Gri Çıtalı serisi, gri tonlarıyla çağdaş iç mekanlara mükemmel uyum sağlayan iç kapı modelidir. Dikey çıta detaylarıyla dinamik bir görünüm yaratır.',
    images: [
      { src: '/kapi/ic-kapi-11/kapi-sahne.webp', alt: 'Modern Gri Çıtalı İç Kapı - Mekan Görünümü', isPrimary: true },
      { src: '/kapi/ic-kapi-11/kapi-detay.webp', alt: 'Modern Gri Çıtalı İç Kapı - Detay' },
      { src: '/kapi/ic-kapi-11/kapi-yakin.webp', alt: 'Modern Gri Çıtalı İç Kapı - Yakın Çekim' },
    ],
    priceRange: { min: 5000, max: 7000, currency: 'TL', note: 'Kasa + Kanat + Pervaz' },
    specs: {
      material: 'MDF üzeri Lake Boya',
      width: '80 cm / 90 cm',
      height: '200 cm / 210 cm',
      thickness: '40 mm',
      lockSystem: 'Manyetik Kilit (Sessiz)',
      insulation: 'Standart',
      color: ['Mat Gri', 'Koyu Gri', 'Açık Gri'],
      warranty: '5 Yıl',
    },
    features: [
      'Dikey Çıta Detay Tasarımı',
      'Mat Lake Boya (3 Kat Astar)',
      'Gizli Menteşe Sistemi',
      'Manyetik Kilit (Sessiz Kapanma)',
      'Modern Minimalist Tasarım',
    ],
    isFeatured: true,
    relatedProducts: ['elegance-beyaz-citali-ic-kapi', 'minimal-beyaz-panel-ic-kapi'],
  },
  {
    id: 'ic-012',
    sku: 'KA-IK-012',
    slug: 'premium-gri-camli-ic-kapi',
    name: 'Premium Gri Camlı İç Kapı',
    category: 'ic-kapilar',
    brand: 'KapıArt Özel Üretim',
    shortDescription: 'Geniş buzlu cam panelli, gri frame, yapı içi ışık geçirgen iç kapı.',
    description: 'Premium Gri Camlı serisi, geniş buzlu cam ve gri çerçevesiyle modern ofis ve otel ortamlarında profesyonel bir görünüm yaratır. Doğal ışık geçişi sağlar.',
    images: [
      { src: '/kapi/ic-kapi-12/kapi-sahne.webp', alt: 'Premium Gri Camlı İç Kapı - Mekan Görünümü', isPrimary: true },
      { src: '/kapi/ic-kapi-12/kapi-detay.webp', alt: 'Premium Gri Camlı İç Kapı - Detay' },
      { src: '/kapi/ic-kapi-12/kapi-yakin.webp', alt: 'Premium Gri Camlı İç Kapı - Yakın Çekim' },
    ],
    priceRange: { min: 7000, max: 10000, currency: 'TL', note: 'Kasa + Kanat + Pervaz' },
    specs: {
      material: 'MDF + Buzlu Temperli Cam',
      width: '80 cm / 90 cm',
      height: '200 cm / 210 cm',
      thickness: '40 mm',
      lockSystem: 'Manyetik Kilit (Sessiz)',
      insulation: 'Standart',
      color: ['Mat Gri', 'Gümüş Gri', 'Antrasit'],
      warranty: '5 Yıl',
    },
    features: [
      'Geniş Buzlu Temperli Cam',
      'Doğal Işık Geçişi',
      'Gizli Menteşe Sistemi',
      'Manyetik Sessiz Kilit',
      'Profesyonel Tasarım',
    ],
    badge: 'Yeni',
    isFeatured: true,
    relatedProducts: ['vista-camli-beyaz-ic-kapi', 'panorama-4-camli-beyaz-ic-kapi'],
  },
  {
    id: 'ic-013',
    sku: 'KA-IK-013',
    slug: 'elegance-antrasit-vitray-ic-kapi',
    name: 'Elegance Antrasit Vitray İç Kapı',
    category: 'ic-kapilar',
    brand: 'KapıArt Özel Üretim',
    shortDescription: 'Dekoratif vitray cam detaylı, antrasit frame, şık iç kapı.',
    description: 'Elegance Antrasit Vitray serisi, vitray cam detaylarıyla klasik sanatı antrasit rengiyle moderne dönüştüren özel iç kapı modelidir. Lüks mekanlara prestij katar.',
    images: [
      { src: '/kapi/ic-kapi-13/kapi-sahne.webp', alt: 'Elegance Antrasit Vitray İç Kapı - Mekan Görünümü', isPrimary: true },
      { src: '/kapi/ic-kapi-13/kapi-yakin.webp', alt: 'Elegance Antrasit Vitray İç Kapı - Yakın Çekim' },
      { src: '/kapi/ic-kapi-13/kapi-detay.webp', alt: 'Elegance Antrasit Vitray İç Kapı - Detay' },
    ],
    priceRange: { min: 8000, max: 11000, currency: 'TL', note: 'Kasa + Kanat + Pervaz' },
    specs: {
      material: 'MDF + Vitray Cam',
      width: '80 cm / 90 cm',
      height: '200 cm / 210 cm',
      thickness: '40 mm',
      lockSystem: 'Silindir Kilit',
      insulation: 'Standart',
      color: ['Antrasit', 'Koyu Gri', 'Mat Siyah'],
      warranty: '5 Yıl',
    },
    features: [
      'Dekoratif Vitray Cam',
      'Antrasit Lake Boya',
      'Lüks Tasarım Çizgisi',
      'Gizli Menteşe Sistemi',
      'Özel Ölçü İmkânı',
    ],
    badge: 'Yeni',
    relatedProducts: ['luna-mese-vitray-camli-ic-kapi', 'royal-beyaz-vitray-camli-ic-kapi'],
  },
  {
    id: 'ic-014',
    sku: 'KA-IK-014',
    slug: 'contemporary-siyah-panel-ic-kapi',
    name: 'Contemporary Siyah Panel İç Kapı',
    category: 'ic-kapilar',
    brand: 'KapıArt Özel Üretim',
    shortDescription: 'Mat siyah lake, geometrik panel detaylı, ultra modern iç kapı.',
    description: 'Contemporary Siyah Panel, saf minimalizmi siyah lake yüzeyiyle sunan avant-garde iç kapı modelidir. Loft ve endüstriyel tasarımlara mükemmel uyum sağlar.',
    images: [
      { src: '/kapi/ic-kapi-14/kapi-sahne.webp', alt: 'Contemporary Siyah Panel İç Kapı - Mekan Görünümü', isPrimary: true },
      { src: '/kapi/ic-kapi-14/kapi-detay.webp', alt: 'Contemporary Siyah Panel İç Kapı - Detay' },
      { src: '/kapi/ic-kapi-14/kapi-yakin.webp', alt: 'Contemporary Siyah Panel İç Kapı - Yakın Çekim' },
    ],
    priceRange: { min: 5500, max: 7500, currency: 'TL', note: 'Kasa + Kanat + Pervaz' },
    specs: {
      material: 'MDF üzeri Lake Boya',
      width: '80 cm / 90 cm',
      height: '200 cm / 210 cm',
      thickness: '40 mm',
      lockSystem: 'Manyetik Kilit (Sessiz)',
      insulation: 'Standart',
      color: ['Mat Siyah', 'Siyah Parlak', 'Koyu Antrasit'],
      warranty: '5 Yıl',
    },
    features: [
      'Mat Siyah Lake Boya',
      'Geometrik Panel Desen',
      'Ultra Modern Tasarım',
      'Gizli Menteşe Sistemi',
      'Minimalist Estetik',
    ],
    badge: 'Popüler',
    isFeatured: true,
    relatedProducts: ['minimal-beyaz-panel-ic-kapi', 'modern-gri-citali-ic-kapi'],
  },
  {
    id: 'ic-015',
    sku: 'KA-IK-015',
    slug: 'luxe-beyaz-desen-ic-kapi',
    name: 'Luxe Beyaz Desen İç Kapı',
    category: 'ic-kapilar',
    brand: 'KapıArt Özel Üretim',
    shortDescription: 'CNC işlemeli kabartma desen, beyaz lake, lüks iç kapı.',
    description: 'Luxe Beyaz Desen serisi, ince CNC kabartma desenleriyle beyaz lake yüzeyinde zarif ve sofistike bir görünüm yaratır. Beş yıldızlı otel ve lüks rezidanslara uygun.',
    images: [
      { src: '/kapi/ic-kapi-15/kapi-sahne.webp', alt: 'Luxe Beyaz Desen İç Kapı - Mekan Görünümü', isPrimary: true },
      { src: '/kapi/ic-kapi-15/kapi-detay.webp', alt: 'Luxe Beyaz Desen İç Kapı - Detay' },
      { src: '/kapi/ic-kapi-15/kapi-yakin.webp', alt: 'Luxe Beyaz Desen İç Kapı - Yakın Çekim' },
    ],
    priceRange: { min: 7500, max: 10500, currency: 'TL', note: 'Kasa + Kanat + Pervaz' },
    specs: {
      material: 'MDF üzeri Lake Boya',
      width: '80 cm / 90 cm',
      height: '200 cm / 210 cm',
      thickness: '40 mm',
      lockSystem: 'Manyetik Kilit (Sessiz)',
      insulation: 'Standart',
      color: ['Mat Beyaz', 'Parlak Beyaz', 'Krem'],
      warranty: '5 Yıl',
    },
    features: [
      'CNC İşlemeli Kabartma Desen',
      'Mat Lake Boya (3 Kat Astar)',
      'Lüks Tasarım Çizgisi',
      'Gizli Menteşe Sistemi',
      'Sofistike Estetik',
    ],
    badge: 'Kampanyalı',
    isFeatured: true,
    relatedProducts: ['flora-beyaz-lake-ic-kapi', 'royal-beyaz-vitray-camli-ic-kapi'],
  },
  {
    id: 'ic-016',
    sku: 'KA-IK-016',
    slug: 'industrial-ceviz-ic-kapi',
    name: 'Industrial Ceviz İç Kapı',
    category: 'ic-kapilar',
    brand: 'KapıArt Özel Üretim',
    shortDescription: 'Açık ceviz laminat, çelik aksesuar, endustri tasarımı iç kapı.',
    description: 'Industrial Ceviz serisi, ceviz laminat kaplama ve çelik aksesuarlarıyla endüstriyel ve loft tasarımlarına mükemmel uyum sağlayan iç kapı modelidir. Sıcak ve güçlü bir karakter sunar.',
    images: [
      { src: '/kapi/ic-kapi-16/kapi-sahne.webp', alt: 'Industrial Ceviz İç Kapı - Mekan Görünümü', isPrimary: true },
      { src: '/kapi/ic-kapi-16/kapi-detay.webp', alt: 'Industrial Ceviz İç Kapı - Detay' },
      { src: '/kapi/ic-kapi-16/kapi-yakin.webp', alt: 'Industrial Ceviz İç Kapı - Yakın Çekim' },
    ],
    priceRange: { min: 6500, max: 9000, currency: 'TL', note: 'Kasa + Kanat + Pervaz' },
    specs: {
      material: 'MDF üzeri CPL Laminat',
      width: '80 cm / 90 cm',
      height: '200 cm / 210 cm',
      thickness: '40 mm',
      lockSystem: 'Silindir Kilit',
      insulation: 'Standart',
      color: ['Açık Ceviz', 'Orta Ceviz', 'Koyu Ceviz'],
      warranty: '5 Yıl',
    },
    features: [
      'Açık Ceviz CPL Laminat',
      'Çelik Aksesuar Detayı',
      'Endüstriyel Tasarım',
      'Dayanıklı Laminat Kaplama',
      'Loft Tasarımlarına Uygun',
    ],
    relatedProducts: ['art-deco-mese-ic-kapi', 'luna-mese-vitray-camli-ic-kapi'],
  },
  {
    id: 'ic-017',
    sku: 'KA-IK-017',
    slug: 'urban-meşe-citali-ic-kapi',
    name: 'Urban Meşe Çıtalı İç Kapı',
    category: 'ic-kapilar',
    brand: 'KapıArt Özel Üretim',
    shortDescription: 'Dikey çıta detaylı, doğal meşe laminat, şehir tasarımı iç kapı.',
    description: 'Urban Meşe Çıtalı serisi, doğal meşe tonlarıyla çağdaş şehir yaşamına uyum sağlayan iç kapı modelidir. Dikey çıtaların dinamikliliği ve doğal ahşap görünümü birleşir.',
    images: [
      { src: '/kapi/ic-kapi-17/kapi-sahne.webp', alt: 'Urban Meşe Çıtalı İç Kapı - Mekan Görünümü', isPrimary: true },
      { src: '/kapi/ic-kapi-17/kapi-yakin.webp', alt: 'Urban Meşe Çıtalı İç Kapı - Yakın Çekim' },
      { src: '/kapi/ic-kapi-17/kapi-detay.webp', alt: 'Urban Meşe Çıtalı İç Kapı - Detay' },
    ],
    priceRange: { min: 6000, max: 8500, currency: 'TL', note: 'Kasa + Kanat + Pervaz' },
    specs: {
      material: 'MDF üzeri CPL Laminat',
      width: '80 cm / 90 cm',
      height: '200 cm / 210 cm',
      thickness: '40 mm',
      lockSystem: 'Silindir Kilit',
      insulation: 'Standart',
      color: ['Doğal Meşe', 'Açık Meşe', 'Gri Meşe'],
      warranty: '5 Yıl',
    },
    features: [
      'Dikey Çıta Detay',
      'Doğal Meşe CPL Laminat',
      'Şehir Tasarımı Çizgisi',
      'Modern Ahşap Görünümü',
      'Özel Ölçü İmkânı',
    ],
    isFeatured: true,
    relatedProducts: ['art-deco-mese-ic-kapi', 'luna-mese-vitray-camli-ic-kapi'],
  },
  {
    id: 'ic-018',
    sku: 'KA-IK-018',
    slug: 'zenith-gri-vitray-ic-kapi',
    name: 'Zenith Gri Vitray İç Kapı',
    category: 'ic-kapilar',
    brand: 'KapıArt Özel Üretim',
    shortDescription: 'Geometrik vitray cam, gri lake frame, premium iç kapı.',
    description: 'Zenith Gri Vitray serisi, geometrik vitray cam tasarımıyla gri lake çerçevesinde modern lüksü sunan iç kapı modelidir. Sanat ve işlevselliği birleştirir.',
    images: [
      { src: '/kapi/ic-kapi-18/kapi-sahne.webp', alt: 'Zenith Gri Vitray İç Kapı - Mekan Görünümü', isPrimary: true },
      { src: '/kapi/ic-kapi-18/kapi-detay.webp', alt: 'Zenith Gri Vitray İç Kapı - Detay' },
      { src: '/kapi/ic-kapi-18/kapi-yakin.webp', alt: 'Zenith Gri Vitray İç Kapı - Yakın Çekim' },
    ],
    priceRange: { min: 8500, max: 12000, currency: 'TL', note: 'Kasa + Kanat + Pervaz' },
    specs: {
      material: 'MDF + Vitray Cam',
      width: '80 cm / 90 cm',
      height: '200 cm / 210 cm',
      thickness: '40 mm',
      lockSystem: 'Manyetik Kilit (Sessiz)',
      insulation: 'Standart',
      color: ['Mat Gri', 'Gümüş Gri', 'Açık Gri'],
      warranty: '5 Yıl',
    },
    features: [
      'Geometrik Vitray Cam Desen',
      'Gri Lake Frame',
      'Premium Tasarım',
      'Sanat ve İşlevsellik Birliği',
      'Sofistike Estetik',
    ],
    badge: 'Yeni',
    isFeatured: true,
    relatedProducts: ['panorama-4-camli-beyaz-ic-kapi', 'premium-gri-camli-ic-kapi'],
  },
  {
    id: 'ic-019',
    sku: 'KA-IK-019',
    slug: 'radiance-krem-panel-ic-kapi',
    name: 'Radiance Krem Panel İç Kapı',
    category: 'ic-kapilar',
    brand: 'KapıArt Özel Üretim',
    shortDescription: 'Mat krem lake, ince kaportuslu panel detaylı, şık iç kapı.',
    description: 'Radiance Krem Panel serisi, sıcak krem tonlarıyla ve ince panel detaylı tasarımıyla rahat ve şık bir atmosfer yaratır. Çoğu iç mekan stiline uyum sağlar.',
    images: [
      { src: '/kapi/ic-kapi-19/kapi-sahne.webp', alt: 'Radiance Krem Panel İç Kapı - Mekan Görünümü', isPrimary: true },
      { src: '/kapi/ic-kapi-19/kapi-detay.webp', alt: 'Radiance Krem Panel İç Kapı - Detay' },
      { src: '/kapi/ic-kapi-19/kapi-yakin.webp', alt: 'Radiance Krem Panel İç Kapı - Yakın Çekim' },
    ],
    priceRange: { min: 5200, max: 7200, currency: 'TL', note: 'Kasa + Kanat + Pervaz' },
    specs: {
      material: 'MDF üzeri Lake Boya',
      width: '80 cm / 90 cm',
      height: '200 cm / 210 cm',
      thickness: '40 mm',
      lockSystem: 'Manyetik Kilit (Sessiz)',
      insulation: 'Standart',
      color: ['Mat Krem', 'Parlak Krem', 'Krem Beyaz'],
      warranty: '5 Yıl',
    },
    features: [
      'Mat Krem Lake Boya (3 Kat Astar)',
      'İnce Panel Detaylı Tasarım',
      'Gizli Menteşe Sistemi',
      'Manyetik Kilit (Sessiz Kapanma)',
      'Çok Amaçlı Tasarım',
    ],
    relatedProducts: ['elegance-beyaz-citali-ic-kapi', 'minimal-beyaz-panel-ic-kapi'],
  },

  // --- VİLLA KAPILARI ---
  {
    id: 'villa-001',
    sku: 'KA-VK-001',
    slug: 'royal-ceviz-villa-kapisi',
    name: 'Royal Ceviz Villa Kapısı',
    category: 'villa-kapilari',
    brand: 'Özel Üretim',
    shortDescription: 'Masif ceviz ahşap, el işçiliği detaylar, çelik iç konstrüksiyon.',
    description: 'Royal serisi villa kapılarımız, masif ceviz ahşaptan usta el işçiliğiyle üretilir. İç konstrüksiyon çelik, dış kaplama masif ahşap yapısıyla hem güvenlik hem estetik sunar.',
    images: [
      { src: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=1000&fit=crop', alt: 'Royal Ceviz Villa Kapısı - Ön Görünüm', isPrimary: true },
      { src: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&h=900&fit=crop', alt: 'Royal Ceviz - Detay' },
      { src: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&h=600&fit=crop&crop=bottom', alt: 'Royal Ceviz - Kol Detayı' },
    ],
    priceRange: { min: 45000, max: 85000, currency: 'TL', note: 'Özel üretim, montaj dahil' },
    specs: {
      material: 'Masif Ceviz + Çelik Konstrüksiyon',
      width: '120 cm / 140 cm / Çift Kanat',
      height: '220 cm / 240 cm',
      thickness: '80 mm',
      lockSystem: 'Çok Noktalı + Parmak İzi',
      insulation: 'Yüksek - 45 dB Ses',
      color: ['Doğal Ceviz', 'Koyu Ceviz', 'İstek Üzerine Boya'],
      warranty: '10 Yıl',
      securityClass: 'RC3',
    },
    features: [
      'Masif Ceviz Ahşap',
      'El İşçiliği Oyma Detaylar',
      'Çelik İç Konstrüksiyon',
      'Özel Ölçü & Tasarım',
      'Pirinc/Krom Aksesuar Seçeneği',
    ],
    badge: 'Sınırlı Stok',
    isFeatured: true,
    relatedProducts: ['modern-aluminyum-villa-kapisi'],
  },
  {
    id: 'villa-002',
    sku: 'KA-VK-002',
    slug: 'modern-aluminyum-villa-kapisi',
    name: 'Modern Alüminyum Villa Kapısı',
    category: 'villa-kapilari',
    brand: 'Özel Üretim',
    shortDescription: 'Alüminyum kompozit, cam detaylı, minimalist tasarım villa kapısı.',
    description: 'Modern Alüminyum Villa Kapısı, çağdaş mimari ile uyum sağlayan minimalist tasarımıyla göz doldurur. Alüminyum kompozit yapısı sayesinde hava koşullarına karşı dayanıklıdır.',
    images: [
      { src: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=1000&fit=crop', alt: 'Modern Alüminyum Villa Kapısı', isPrimary: true },
      { src: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&h=900&fit=crop', alt: 'Modern Alüminyum - Detay' },
    ],
    priceRange: { min: 35000, max: 65000, currency: 'TL', note: 'Özel üretim, montaj dahil' },
    specs: {
      material: 'Alüminyum Kompozit + Cam',
      width: '120 cm / Çift Kanat',
      height: '220 cm / 240 cm',
      thickness: '75 mm',
      lockSystem: 'Çok Noktalı Kilit + Motorlu',
      insulation: 'Yüksek - 40 dB Ses',
      color: ['Antrasit', 'Siyah', 'Gümüş', 'Bronz'],
      warranty: '10 Yıl',
      securityClass: 'RC2',
    },
    features: [
      'Alüminyum Kompozit Yapı',
      'Cam Detaylar',
      'Motorlu Kilit Seçeneği',
      'Hava Koşullarına Dayanıklı',
    ],
    relatedProducts: ['royal-ceviz-villa-kapisi'],
  },

  // --- AMERİKAN PANEL ---
  {
    id: 'panel-001',
    sku: 'KA-AP-001',
    slug: 'klasik-amerikan-panel-kapi',
    name: 'Klasik Amerikan Panel Kapı',
    category: 'amerikan-panel-kapilar',
    brand: 'KapıArt',
    shortDescription: 'Ekonomik, dayanıklı ve kolay montajlı amerikan panel kapı.',
    description: 'Klasik Amerikan Panel Kapı, bütçe dostu fiyatıyla ve kolay montajıyla en popüler iç kapı seçeneklerinden biridir. 8 farklı model ve renk seçeneğiyle her mekana uyum sağlar.',
    images: [
      { src: 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&h=1000&fit=crop&bri=5', alt: 'Klasik Amerikan Panel Kapı', isPrimary: true },
      { src: 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=1200&h=900&fit=crop&bri=5', alt: 'Amerikan Panel - Detay' },
    ],
    priceRange: { min: 2000, max: 3500, currency: 'TL', note: 'Kasa + Kanat' },
    specs: {
      material: 'HDF Panel',
      width: '80 cm / 90 cm',
      height: '200 cm',
      thickness: '35 mm',
      lockSystem: 'Standart Silindir Kilit',
      insulation: 'Temel',
      color: ['Beyaz', 'Krem', 'Ceviz', 'Meşe'],
      warranty: '3 Yıl',
    },
    features: ['Ekonomik Fiyat', '8 Model Seçeneği', 'Kolay Montaj', 'HDF Dayanıklılık'],
    badge: 'Çok Satan',
    isFeatured: true,
    relatedProducts: ['elegance-beyaz-citali-ic-kapi'],
  },

  // --- CAM KAPILAR ---
  {
    id: 'cam-001',
    sku: 'KA-CM-001',
    slug: 'temperli-surgulu-cam-kapi',
    name: 'Temperli Sürgülü Cam Kapı',
    category: 'cam-kapilar',
    brand: 'KapıArt',
    shortDescription: 'Temperli cam, alüminyum raylı sürgülü kapı sistemi.',
    description: 'Temperli Sürgülü Cam Kapı, modern mekanlar için ideal bir çözüm sunar. Alüminyum ray sistemi ile sessiz ve kolay kullanım, temperli cam ile güvenlik sağlar.',
    images: [
      { src: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=800&h=1000&fit=crop&bri=-5', alt: 'Temperli Sürgülü Cam Kapı', isPrimary: true },
      { src: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=1200&h=900&fit=crop&bri=-5', alt: 'Sürgülü Cam - Ray Sistemi' },
    ],
    priceRange: { min: 8000, max: 15000, currency: 'TL', note: 'Ray sistemi dahil' },
    specs: {
      material: '10mm Temperli Cam + Alüminyum Ray',
      width: '80 cm / 90 cm / 100 cm',
      height: '200 cm / 210 cm',
      thickness: '10 mm cam',
      lockSystem: 'Cam Kapı Kilidi',
      insulation: 'Temel',
      color: ['Şeffaf', 'Buzlu', 'Füme', 'Bronz'],
      warranty: '5 Yıl',
    },
    features: [
      'Temperli Güvenlik Camı',
      'Alüminyum Ray Sistemi',
      'Sessiz Sürgü Mekanizması',
      'Modern Minimalist Tasarım',
    ],
    isFeatured: true,
    relatedProducts: ['vista-camli-beyaz-ic-kapi'],
  },

  // --- YANGIN KAPILARI ---
  {
    id: 'yangin-001',
    sku: 'KA-YK-001',
    slug: 'yangin-kapisi-60dk',
    name: 'Yangın Kapısı - 60 Dakika',
    category: 'yangin-kapilari',
    brand: 'KapıArt',
    shortDescription: '60 dakika yangın dayanımlı, CE ve TSE belgeli yangın kapısı.',
    description: '60 Dakika Yangın Kapısı, yangın yönetmeliğine tam uyumlu, CE ve TSE belgeli profesyonel yangın kapısıdır. Panik bar donanımı ve otomatik kapanma mekanizması standart olarak dahildir.',
    images: [
      { src: 'https://images.unsplash.com/photo-1600573472591-ee6b68d14c68?w=800&h=1000&fit=crop', alt: '60 Dakika Yangın Kapısı', isPrimary: true },
      { src: 'https://images.unsplash.com/photo-1600573472591-ee6b68d14c68?w=1200&h=900&fit=crop', alt: 'Yangın Kapısı - Panik Bar' },
    ],
    priceRange: { min: 8000, max: 14000, currency: 'TL', note: 'Panik bar dahil' },
    specs: {
      material: 'Galvaniz Çelik + Yangın Yalıtımı',
      width: '90 cm / 100 cm / 120 cm',
      height: '200 cm / 210 cm',
      thickness: '65 mm',
      lockSystem: 'Panik Bar + Silindir Kilit',
      insulation: 'Yangın Yalıtımı (Taş Yünü)',
      color: ['RAL 7035 Gri', 'RAL 9010 Beyaz'],
      warranty: '5 Yıl',
      fireRating: '60 Dakika',
    },
    features: [
      '60 Dakika Yangın Dayanımı',
      'CE & TSE Belgeli',
      'Panik Bar Donanımlı',
      'Otomatik Kapanma Mekanizması',
      'Duman Sızdırmazlık Contası',
    ],
    relatedProducts: ['yangin-kapisi-90dk'],
  },
  {
    id: 'yangin-002',
    sku: 'KA-YK-002',
    slug: 'yangin-kapisi-90dk',
    name: 'Yangın Kapısı - 90 Dakika',
    category: 'yangin-kapilari',
    brand: 'KapıArt',
    shortDescription: '90 dakika yangın dayanımlı, yüksek güvenlikli profesyonel yangın kapısı.',
    description: '90 Dakika Yangın Kapısı, yüksek riskli alanlar için tasarlanmış profesyonel yangın kapısıdır. Ekstra kalın yapısı ve gelişmiş yalıtım ile 90 dakika yangın dayanımı sağlar.',
    images: [
      { src: 'https://images.unsplash.com/photo-1600573472591-ee6b68d14c68?w=800&h=1000&fit=crop&sat=-30', alt: '90 Dakika Yangın Kapısı', isPrimary: true },
      { src: 'https://images.unsplash.com/photo-1600573472591-ee6b68d14c68?w=1200&h=900&fit=crop&sat=-30', alt: 'Yangın Kapısı 90dk - Detay' },
    ],
    priceRange: { min: 12000, max: 20000, currency: 'TL', note: 'Panik bar dahil' },
    specs: {
      material: 'Galvaniz Çelik (Çift Katlı) + Yangın Yalıtımı',
      width: '90 cm / 100 cm / 120 cm / Çift Kanat',
      height: '200 cm / 210 cm / 220 cm',
      thickness: '80 mm',
      lockSystem: 'Panik Bar + Anti-panik Kilit',
      insulation: 'Yüksek Yangın Yalıtımı (Seramik Elyaf)',
      color: ['RAL 7035 Gri', 'RAL 9010 Beyaz', 'RAL 7016 Antrasit'],
      warranty: '7 Yıl',
      fireRating: '90 Dakika',
    },
    features: [
      '90 Dakika Yangın Dayanımı',
      'CE & TSE Belgeli',
      'Çift Kanat Seçeneği',
      'Elektromanyetik Tutucu Uyumlu',
      'Yangın Alarm Entegrasyonu',
    ],
    badge: 'Popüler',
    relatedProducts: ['yangin-kapisi-60dk'],
  },
];

// Proje Galerisi (montaj öncesi/sonrası)
export const projectGallery = [
  {
    id: 1,
    title: 'Bahçeşehir Villa - Çelik Kapı Montajı',
    before: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop&sat=-80',
    after: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop',
    category: 'Çelik Kapı',
    description: 'Eski ahşap kapının çelik kapı ile değişimi.',
  },
  {
    id: 2,
    title: 'Ataşehir Rezidans - İç Kapı Yenileme',
    before: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&h=600&fit=crop&sat=-80',
    after: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&h=600&fit=crop',
    category: 'İç Kapı',
    description: 'Tüm daire iç kapılarının lake beyaz modellere değişimi.',
  },
  {
    id: 3,
    title: 'Sapanca Villa - Masif Ceviz Giriş Kapısı',
    before: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop&sat=-80',
    after: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop',
    category: 'Villa Kapısı',
    description: 'Özel tasarım masif ceviz villa giriş kapısı montajı.',
  },
  {
    id: 4,
    title: 'Beylikdüzü AVM - Yangın Kapısı Projesi',
    before: 'https://images.unsplash.com/photo-1600573472591-ee6b68d14c68?w=800&h=600&fit=crop&sat=-80',
    after: 'https://images.unsplash.com/photo-1600573472591-ee6b68d14c68?w=800&h=600&fit=crop',
    category: 'Yangın Kapısı',
    description: '48 adet yangın kapısı montajı ve sertifikalandırma.',
  },
  {
    id: 5,
    title: 'Kadıköy Ofis - Cam Kapı Sistemi',
    before: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=800&h=600&fit=crop&sat=-80',
    after: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=800&h=600&fit=crop',
    category: 'Cam Kapı',
    description: 'Ofis bölme ve sürgülü cam kapı sistemi kurulumu.',
  },
  {
    id: 6,
    title: 'Pendik Konut - Amerikan Panel Değişimi',
    before: 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&h=600&fit=crop&sat=-80',
    after: 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&h=600&fit=crop',
    category: 'Amerikan Panel',
    description: '5 adet amerikan panel kapı değişimi ve montajı.',
  },
];

export function formatPrice(price: number): string {
  return new Intl.NumberFormat('tr-TR').format(price);
}
